### ISSUE TITLE
Running a basic test case doesn't work

### ISSUE THREAD

**Issue by kss-espeo** [hyperledger-labs/trusted-compute-framework#61]
Hi,

Kris, a Gardener dev here. We would like to start the work to adapt our monitor frontend to TCF. In order to do that, I tried to set up TCF on my local machine to figure out how to integrate with TCF. It however hasnt worked for me, as described below:

1. I start TCF HW mode with `sudo docker-compose -f docker-compose-sgx.yaml`
2. I open TCF virtual environment inside docker container with `source _dev/bin/activate`
3. I run a test scenario with `python3 Demo.py --input_dir ./json_requests/ --connect_uri "http://localhost:1947" work_orders/output.json`
5. Expected: A test passes and some output is shown in docker logs
6. Actual: A test fails with a following error:

```
(_dev) root@77d67368567a:/project/TrustedComputeFramework/tests# python3 Demo.py --input_dir ./json_requests/ \
>         --connect_uri "http://localhost:1947" work_orders/output.json
[11:09:54 INFO    __main__] ***************** INTEL TRUSTED COMPUTE FRAMEWORK (TCF)*****************
[11:09:54 INFO    __main__] Load Json Directory from ./json_requests/
[11:09:54 INFO    __main__] Execute work order
[11:09:54 INFO    __main__] ------------------Input file name: json_01.json ---------------

[11:09:54 INFO    __main__] *********Request Json********* 
{"jsonrpc": "2.0", "method": "WorkerLookUp", "id": 1, "params": {"workerType": 1, "workOrderId": null}}

[11:09:54 INFO    __main__] **********Received Response*********
{'jsonrpc': '2.0', 'id': 1, 'result': {'totalCount': 0, 'lookupTag': '', 'ids': []}}

[11:09:54 INFO    __main__] ------------------Input file name: json_02.json ---------------

[11:09:54 WARNING STDERR] Traceback (most recent call last):
[11:09:54 WARNING STDERR]   File "Demo.py", line 256, in <module>
[11:09:54 WARNING STDERR] Main()
[11:09:54 WARNING STDERR]   File "Demo.py", line 253, in Main
[11:09:54 WARNING STDERR] LocalMain(config)
[11:09:54 WARNING STDERR]   File "Demo.py", line 92, in LocalMain
[11:09:54 WARNING STDERR] worker_id = response["result"]["ids"][0]
[11:09:54 WARNING STDERR] IndexError
[11:09:54 WARNING STDERR] :
[11:09:54 WARNING STDERR] list index out of range

```
and following output in docker logs:
```
tcf    | [10:24:04 INFO    __main__] TCS Listener started on port 1947
tcf    | [11:09:54 INFO    __main__] Received a new request from the client
tcf    | [11:09:54 INFO    tcs_worker_registry_handler] Received Worker request : WorkerLookUp
tcf    | [11:09:54 INFO    __main__] response[application/json]: {"jsonrpc": "2.0", "id": 1, "result": {"totalCount": 0, "lookupTag": "", "ids": []}}
```

Looks like a bug, though do let me know if I set something up incorrectly, please!

Thanks,
KSS

**Comment by danintel** [comment]
KSS,

I just ran the same test and it works (see below).  The difference is when you run it, your response from the WorkerLookUp in json_01.json is:

{'jsonrpc': '2.0', 'id': 1, 'result': {'totalCount': 0, 'lookupTag': '', 'ids': []}}

While I get:
{'jsonrpc': '2.0', 'id': 1, 'result': {'totalCount': 1, 'lookupTag': '4d465977454159484b6f5a497a6a3043415159464b34454541416f44516741457a4e7377386656766f3146794a453130542f67396e45696d346c454e2b74455131714d7751426b6d39746b33624d5169562b6d646b2b557074584d4e746c594e57796f726a47384454574669535033794273486473513d3d', 'ids': ['4d465977454159484b6f5a497a6a3043415159464b34454541416f44516741457a4e7377386656766f3146794a453130542f67396e45696d346c454e2b74455131714d7751426b6d39746b33624d5169562b6d646b2b557074584d4e746c594e57796f726a47384454574669535033794273486473513d3d']}}

In other words, when you run it, it cannot find a worker (the totalCount for you is 0), but when I run it I have a worker.

My guess is when Docker runs scripts/tcs_startup.sh, which starts the TCF Enclave Manager and the TCF Listener, that one of them failed to start or had some error running.  Most commonly this is because you are missing some prerequisite package.  All the required packages should be installed with docker/Dockerfile.tcf-dev , but we may be missing a package. Look in the log for “start the lmdb server”, “Starting Enclave manager”, and “Starting Listener” and see if there are any errors starting one or the other.

Dan


jackson tcf (master) $ sudo docker exec -it tcf bash
[sudo] password for dano:
root@9161f50f279c:/project/TrustedComputeFramework/tools/build# source _dev/bin/activate
(_dev) root@9161f50f279c:/project/TrustedComputeFramework/tools/build#  cd $TCF_HOME/tests
(_dev) root@9161f50f279c:/project/TrustedComputeFramework/tests# python3 Demo.py --input_dir ./json_requests/ \
> --connect_uri "http://localhost:1947" work_orders/output.json
[16:13:53 INFO    __main__] ***************** INTEL TRUSTED COMPUTE FRAMEWORK (TCF)*****************
[16:13:53 INFO    __main__] Load Json Directory from ./json_requests/
[16:13:53 INFO    __main__] Execute work order
[16:13:53 INFO    __main__] ------------------Input file name: json_01.json ---------------

[16:13:53 INFO    __main__] *********Request Json*********
{"jsonrpc": "2.0", "method": "WorkerLookUp", "id": 1, "params": {"workerType": 1, "workOrderId": null}}

[16:13:53 INFO    __main__] **********Received Response*********
{'jsonrpc': '2.0', 'id': 1, 'result': {'totalCount': 1, 'lookupTag': '4d465977454159484b6f5a497a6a3043415159464b34454541416f44516741457a4e7377386656766f3146794a453130542f67396e45696d346c454e2b74455131714d7751426b6d39746b33624d5169562b6d646b2b557074584d4e746c594e57796f726a47384454574669535033794273486473513d3d', 'ids': ['4d465977454159484b6f5a497a6a3043415159464b34454541416f44516741457a4e7377386656766f3146794a453130542f67396e45696d346c454e2b74455131714d7751426b6d39746b33624d5169562b6d646b2b557074584d4e746c594e57796f726a47384454574669535033794273486473513d3d']}}

[16:13:53 INFO    __main__] ------------------Input file name: json_02.json ---------------

[16:13:53 INFO    __main__] **********Worker details Updated with Worker ID*********
{"jsonrpc": "2.0", "method": "WorkerRetrieve", "id": 2, "params": {"workerId": "4d465977454159484b6f5a497a6a3043415159464b34454541416f44516741457a4e7377386656766f3146794a453130542f67396e45696d346c454e2b74455131714d7751426b6d39746b33624d5169562b6d646b2b557074584d4e746c594e57796f726a47384454574669535033794273486473513d3d"}}

[16:13:53 INFO    __main__] *********Request Json*********
{"jsonrpc": "2.0", "method": "WorkerRetrieve", "id": 2, "params": {"workerId": "4d465977454159484b6f5a497a6a3043415159464b34454541416f44516741457a4e7377386656766f3146794a453130542f67396e45696d346c454e2b74455131714d7751426b6d39746b33624d5169562b6d646b2b557074584d4e746c594e57796f726a47384454574669535033794273486473513d3d", "workOrderId": null}}

[16:13:53 INFO    __main__] **********Received Response*********
{'jsonrpc': '2.0', 'id': 2, 'result': {'workerType': 1, 'organizationId': 'aabbcc1234ddeeff', 'applicationTypeId': '11aa22bb33cc44dd', 'details': {'workOrderSyncUri': 'http://localhost:8080', 'workOrderAsyncUri': 'http://localhost:8080', 'workOrderPullUri': 'http://localhost:8080', 'workOrderNotifyUri': 'http://localhost:8080', 'receiptInvocationUri': 'http://localhost:8080', 'workOrderInvocationAddress': '', 'receiptInvocationAddress': '', 'fromAddress': '', 'hashingAlgorithm': 'SHA-256', 'signingAlgorithm': 'SECP256K1', 'keyEncryptionAlgorithm': 'RSA-OAEP-3072', 'dataEncryptionAlgorithm': 'AES-GCM-256', 'workOrderPayloadFormats': 'JSON-RPC', 'workerTypeData': {'verificationKey': '-----BEGIN PUBLIC KEY-----\nMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEzNsw8fVvo1FyJE10T/g9nEim4lEN+tEQ\n1qMwQBkm9tk3bMQiV+mdk+UptXMNtlYNWyorjG8DTWFiSP3yBsHdsQ==\n-----END PUBLIC KEY-----\n', 'extendedMeasurements': ['DEADBEEF00000000DEADBEEF0000000000000000000000000000000000000000', 'E84926A7695416A555810126A7B7AA734626F9C3374019AC06241FB37D00F966'], 'proofDataType': 'TEE-SGX-IAS', 'proofData': '', 'encryptionKey': '-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEA1UN7OQtzh8ou0EFW9KlYZto7vyxCHOI+PHzK45qgcE7cqrEzXjlV\n9cf6QAqhWnzqrEMrWI2CFEPBO2p9VxOCKR76hwEKEBy1uqdXkztXuR6JH2PYje5w\nZoGgIoBpEdtZX2OD13McN6Xq4KLoHTdw1WYwruuSjo47jJjT31SFJjgI5rs+vXnX\nR3I9ZuGkDo2rbQb2h9l3qABzRXLO4kMz5G/CPerrM8qihxIPpApCcUTwP8dXC7CX\nO3XX3wy4QJ6sIc1IYh/QcjfkK+oQO/t3uqhfxT0rjdF17g98eoGlP4fXAm1KtYuq\nFQnjWwk2zhuXIh/H38SYwgvnHMQqrVrHnQIDAQAB\n-----END RSA PUBLIC KEY-----\n', 'encryptionKeySignature': ''}}, 'status': 1}}

[16:13:53 INFO    worker.worker_details] *********Updating Worker Details*********
[16:13:53 INFO    worker.worker_details] Hashing Algorithm : SHA-256
[16:13:53 INFO    worker.worker_details] Signing Algorithm : SECP256K1

**Comment by kss-espeo** [comment]
I think you're right @danintel . At least, some log output that I missed seems to confirm your words:
```
Starting Listener..
Listener started
[10:34:04 ERROR   __main__] failed to initialize enclave; Failed to initialize quote in enclave constructor: SGX ERROR: SGX_ERROR_BUSY
Traceback (most recent call last):
  File "/project/TrustedComputeFramework/examples/enclave_manager/tcf_enclave_manager/enclave_manager.py", line 332, in start_enclave_manager
    extended_measurements = enclave_helper.initialize_enclave(config.get("EnclaveModule"))
  File "/project/TrustedComputeFramework/examples/enclave_manager/tcf_enclave_manager/tcf_enclave_helper.py", line 35, in initialize_enclave
    return tcf_enclave.initialize_with_configuration(enclave_config)
  File "/project/TrustedComputeFramework/examples/enclave_manager/tcf_enclave_manager/tcf_enclave_bridge.py", line 134, in initialize_with_configuration
    _tcf_enclave_info = enclave.tcf_enclave_info(signed_enclave, config['spid'], int(config['num_of_enclaves']))
  File "/project/TrustedComputeFramework/tools/build/_dev/lib/python3.6/site-packages/tcf_enclave_manager-0.0.1.dev1-py3.6-linux-x86_64.egg/tcf_enclave_manager/tcf_enclave.py", line 451, in __init__
    this = _tcf_enclave.new_tcf_enclave_info(enclaveModulePath, spid, num_of_enclaves)
SystemError: Failed to initialize quote in enclave constructor: SGX ERROR: SGX_ERROR_BUSY
Initializing SGX TCF enclave
Enclave path: /project/TrustedComputeFramework/tc/sgx/trusted_worker_manager/enclave/build/lib/libtcf-enclave.signed.so
SPID: DEADBEEF00000000DEADBEEF00000000
[10:34:04 INFO    __main__] TCS Listener started on port 1947

```
Any hints on how to go about resolving that? I made sure that no processes that could be interacting with SGX are not up, except from TCF of course.

**Comment by kss-espeo** [comment]
I've been using SGX HW. It worked after setting `spid`, `ias_api_key` and commenting out `https_proxy`  in `tcf.config.toml` . Maybe it's worthwhile to put that in documentation.

Thanks for your help @danintel @manojgop

**Comment by danintel** [comment]
I added notes to
https://github.com/hyperledger-labs/trusted-compute-framework/blob/master/PREREQUISITES.md

**Comment by danintel** [comment]
Also make sure there is no proxy setting in `/etc/aesmd.conf`
